import streamlit as st
import yfinance as yf
import pandas as pd
import requests
import plotly.graph_objects as go
from indicators import calculate_advanced_indicators
from ai_engine import generate_trading_signal

st.set_page_config(page_title="AI Multi-Segment Trading Terminal", layout="wide")

st.title("🛡️ Institutional Multi-Segment AI System")
st.caption("Real-time Trading Terminal supporting Intraday, Options, MCX Commodities & Delivery Segments")

# Sidebar Segment Selection
st.sidebar.markdown("### 🌐 Market Segment")
segment = st.sidebar.selectbox(
    "Select Segment:", 
    ["Intraday (Equity)", "Options (Index/Stock)", "MCX (Commodity)", "Delivery (Long Term)"]
)

# Segment-wise default ticker assistance
if segment == "Intraday (Equity)":
    default_ticker, default_interval, default_period = "RELIANCE.NS", "15m", "5d"
elif segment == "Options (Index/Stock)":
    default_ticker, default_interval, default_period = "^NSEI", "5m", "1d"
elif segment == "MCX (Commodity)":
    default_ticker, default_interval, default_period = "GC=F", "15m", "5d"
else:
    default_ticker, default_interval, default_period = "TCS.NS", "1d", "1y"

st.sidebar.markdown("### 🎛️ Terminal Controls")
ticker = st.sidebar.text_input("Asset Ticker Symbol:", value=default_ticker).strip().upper()
interval = st.sidebar.selectbox("Execution Frequency (Interval):", ["1m", "5m", "15m", "1h", "1d"], index=["1m", "5m", "15m", "1h", "1d"].index(default_interval))
period = st.sidebar.selectbox("Lookback Window (Period):", ["1d", "5d", "1mo", "3mo", "1y"], index=["1d", "5d", "1mo", "3mo", "1y"].index(default_period))

# Smart Guard against Intraday Data limitations
if interval in ["1m", "5m", "15m"] and period in ["3mo", "1y"]:
    st.sidebar.warning(f"⚠️ `{interval}` के लिए `{period}` इतिहास उपलब्ध नहीं है। इसे `5d` पर सेट किया जा रहा. है।")
    period = "5d"

if st.sidebar.button("⚡ Execute Deep Intelligence Scan", use_container_width=True):
    with st.spinner(f"Scanning {segment} matrices for {ticker}..."):
        try:
            # 🛡️ Anti-Blocking Session Engine Configuration
            # यह ब्लॉक कोड याहू फाइनेंस की ब्लॉक पॉलिसी को बायपास करता है
            custom_session = requests.Session()
            custom_session.headers.update({
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
                'Accept-Language': 'en-US,en;q=0.5',
                'Origin': 'https://yahoo.com',
                'Referer': 'https://yahoo.com'
            })
            
            # Download market data using custom masked session
            df = yf.download(tickers=ticker, period=period, interval=interval, session=custom_session, progress=False)
            
            # Universal fallback for intraday connection stability
            if (df is None or df.empty) and interval in ["1m", "5m", "15m"]:
                df = yf.download(tickers=ticker, period="5d", interval=interval, session=custom_session, progress=False)
                
            if df is None or df.empty or len(df) < 2:
                st.error("❌ Data Engine Error: इस सिंबल का लाइव डेटा याहू सर्वर ने ब्लॉक कर दिया है या सिंबल गलत है।")
                st.info("💡 टिप्स: यदि सिंबल सही है, तो 2-3 बार बटन दबाकर दोबारा ट्राई करें ताकि क्लाउड सर्वर नया IP एड्रेस ले सके।")
            else:
                # Process data through pipelines safely
                df = calculate_advanced_indicators(df)
                trade_setup = generate_trading_signal(df, ticker, segment)
                
                # Handling multi-index columns securely if generated by yfinance
                if isinstance(df.columns, pd.MultiIndex):
                    df.columns = df.columns.droplevel(1)
                    
                latest_row = df.iloc[-1]
                
                # Dynamic index handling for safe value extraction
                close_val = float(latest_row['Close'].iloc[0]) if hasattr(latest_row['Close'], 'iloc') and isinstance(latest_row['Close'], pd.Series) else float(latest_row['Close'])
                
                # Currency Sign Identification
                currency_symbol = "$" if any(x in ticker for x in ["=", "^"]) and ".NS" not in ticker else "₹"
                
                # Metric Grid Setup
                m1, m2, m3, m4 = st.columns(4)
                m1.metric(f"LTP ({ticker})", f"{currency_symbol}{close_val:.2f}")
                m2.metric("Verdict Signal", trade_setup['signal'])
                m3.metric("🎯 Target Level", f"{currency_symbol}{trade_setup['target']:.2f}" if trade_setup['target'] > 0 else "N/A")
                m4.metric("🛑 Stoploss Level", f"{currency_symbol}{trade_setup['sl']:.2f}" if trade_setup['sl'] > 0 else "N/A")
                
                if "HOLD" not in trade_setup['signal']:
                    st.success(f"📱 WhatsApp Alert Triggered for {segment} Setup!")
                    
                st.info(f"**AI Strategy Engine Log:** {trade_setup['reason']}")
                
                # Render High-Fidelity Candlestick Chart
                fig = go.Figure()
                fig.add_trace(go.Candlestick(x=df.index, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'], name='Price Action'))
                
                if 'BB_Upper' in df.columns and 'BB_Lower' in df.columns:
                    fig.add_trace(go.Scatter(x=df.index, y=df['BB_Upper'], line=dict(color='rgba(255,255,255,0.3)', width=1), name='BB Upper'))
                    fig.add_trace(go.Scatter(x=df.index, y=df['BB_Lower'], line=dict(color='rgba(255,255,255,0.3)', width=1), name='BB Lower'))
                
                fig.update_layout(template="plotly_dark", height=500, xaxis_rangeslider_visible=False, margin=dict(l=10, r=10, t=10, b=10))
                st.plotly_chart(fig, use_container_width=True)
                
        except Exception as e:
            st.error(f"Ecosystem Crash Error: {str(e)}")
